### ISSUE TITLE
Use Real time meaning of function names

### ISSUE THREAD

**Issue by gmnikesh** [jaglinux/de-tweet#2]
Update the label name of the functions in the smart contract to give real time meaning.
ex: fLike as fTweetLike;
     fFollow as fUserToFollow
     getFollowers as getUserFollowers
     getLikes as getTweetLikes

**Comment by jaglinux** [comment]
Fixed by https://github.com/jaglinux/de-tweet/commit/3c47de504b3efaeaf0684da82dc22b038a1c8d30
